apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i4x5oso-t-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i4x5oso-t-go 
  name: i4x5oso-t-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i4x5oso-t-go 
